### ISSUE TITLE
can't get this to work at all

### ISSUE THREAD

**Issue by qwksilver** [donoftime/audible-goodreads#1]
all i get are errors everywhere

**Comment by donoftime** [comment]
There is a usage section in the readme that lays out the prerequisites, including commands to set up audible-cli. 

That said, the audible-cli project has since implemented the same idea over in that project so you might want to use that instead!

Here's the cmd I mean: https://github.com/mkb79/audible-cli/blob/master/plugin_cmds/cmd_goodreads-transform.py
